#!/usr/bin/env python3
"""Generate original lookups for the frozen Node URL normalization profile.

This profile contains only extracted CCC/decomposition/composition data. Its observed
normalization behavior is qualified against the pinned binary, not inferred
from the upstream source algorithms. Unicode 17 PinnedNFC is independent.
"""
import argparse
from URLOracle import normalization_inputs as shared_inputs
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE_SHA256 = '9cb7782123a2f08f8a69a8ec702ff7910cff69cd03773e6d665d79ed5a4b327c'
SOURCE_SHA256 = 'ac8fba37ceddb7c10ca5a24fd57a0f0a0ca32cd3d391e40c6f9f6b7af3801fd4'
OUTPUT = ROOT / 'Sources/Lokalized/Data/IDNACompatibilityNormalizationTables.swift'


def sha(value):
    return hashlib.sha256(value).hexdigest()


def load_profile(reference_directory=ROOT / 'Reference'):
    directory = Path(reference_directory) / 'IDNA-Compatibility'
    raw = (directory / 'normalization-profile.json').read_bytes()
    if sha(raw) != PROFILE_SHA256:
        raise ValueError('IDNA normalization compatibility profile digest differs')
    profile = json.loads(raw)
    if profile['propertyDataSource']['sha256'] != SOURCE_SHA256 or profile['compatibilityAuthority']['nodeVersion'] != 'v26.5.0':
        raise ValueError('IDNA normalization compatibility authority differs')
    ranges = profile['properties']['combiningClasses']
    pairs = profile['properties']['compositionPairs']
    decompositions = profile['properties']['decompositions']
    if len(ranges) != 388 or len(pairs) != 941 or pairs != sorted(pairs) or len({(first, second) for first, second, _ in pairs}) != len(pairs):
        raise ValueError('IDNA normalization compatibility inventory differs')
    if len(decompositions) != 2061 or decompositions != sorted(decompositions) or len({scalar for scalar, _ in decompositions}) != 2061:
        raise ValueError('IDNA normalization decomposition inventory differs')
    previous = -1
    for first, last, value in ranges:
        if not previous < first <= last <= 0x10FFFF or not 0 < value < 256:
            raise ValueError('IDNA normalization compatibility CCC ranges differ')
        previous = last
    spec = importlib.util.spec_from_file_location('idna_property_generator', ROOT / 'Tools/generate_idna_compatibility.py')
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    _, license_text = generator.load_profile(reference_directory)
    return profile, license_text


def generate(profile, license_text):
    ranges = ''.join(f'{first:06x}{last:06x}{value:02x}' for first, last, value in profile['properties']['combiningClasses'])
    pairs = ''.join(f'{first:06x}{second:06x}{result:06x}' for first, second, result in profile['properties']['compositionPairs'])
    decomposition_rows, decomposition_values = [], []
    for scalar, values in profile['properties']['decompositions']:
        decomposition_rows.append(f'{scalar:06x}{len(decomposition_values):06x}{len(values):06x}')
        decomposition_values.extend(values)
    decompositions = ''.join(decomposition_rows)
    decomposition_scalars = ''.join(f'{scalar:06x}' for scalar in decomposition_values)
    notice = '\n'.join('// ' + line if line else '//' for line in license_text.rstrip().splitlines())
    return f'''// Generated by Tools/generate_idna_normalization_compatibility.py. Do not edit.
// Separately pinned Node 26.5.0 URL normalization data, not Unicode 17 NFC.
// Data provenance, binary authority and notice: Reference/IDNA-Compatibility.
// Original compact lookups; no upstream executable normalizer is vendored.
{notice}
package enum IDNACompatibilityNormalizationTables {{
    private static let combiningClasses: StaticString = "{ranges}"
    private static let compositionPairs: StaticString = "{pairs}"
    private static let decompositions: StaticString = "{decompositions}"
    private static let decompositionScalars: StaticString = "{decomposition_scalars}"
    package static func decomposition(_ scalar: UInt32) -> [UInt32]? {{
        let bytes = decompositions.utf8Start
        var low = 0, high = decompositions.utf8CodeUnitCount / 18
        while low < high {{
            let middle = low + (high - low) / 2, offset = middle * 18
            let candidate = hex(bytes, offset, 6)
            if scalar < candidate {{ high = middle }}
            else if scalar > candidate {{ low = middle + 1 }}
            else {{
                let start = Int(hex(bytes, offset + 6, 6)), count = Int(hex(bytes, offset + 12, 6))
                return (start..<(start + count)).map {{ hex(decompositionScalars.utf8Start, $0 * 6, 6) }}
            }}
        }}
        return nil
    }}
    package static func combiningClass(_ scalar: UInt32) -> UInt8 {{
        guard scalar <= 0x10ffff else {{ return 0 }}
        let bytes = combiningClasses.utf8Start
        var low = 0, high = combiningClasses.utf8CodeUnitCount / 14
        while low < high {{
            let middle = low + (high - low) / 2, offset = middle * 14
            if scalar < hex(bytes, offset, 6) {{ high = middle }}
            else if scalar > hex(bytes, offset + 6, 6) {{ low = middle + 1 }}
            else {{ return UInt8(hex(bytes, offset + 12, 2)) }}
        }}
        return 0
    }}
    package static func composition(_ first: UInt32, _ second: UInt32) -> UInt32? {{
        let bytes = compositionPairs.utf8Start
        var low = 0, high = compositionPairs.utf8CodeUnitCount / 18
        while low < high {{
            let middle = low + (high - low) / 2, offset = middle * 18
            let a = hex(bytes, offset, 6), b = hex(bytes, offset + 6, 6)
            if first < a || (first == a && second < b) {{ high = middle }}
            else if first > a || (first == a && second > b) {{ low = middle + 1 }}
            else {{ return hex(bytes, offset + 12, 6) }}
        }}
        return nil
    }}
    private static func hex(_ bytes: UnsafePointer<UInt8>, _ offset: Int, _ digits: Int) -> UInt32 {{
        var value: UInt32 = 0
        for index in offset..<(offset + digits) {{
            let byte = bytes[index]
            value = (value << 4) | UInt32(byte <= 57 ? byte - 48 : byte - 87)
        }}
        return value
    }}
}}
'''


def normalization_discriminant_inputs(reference_directory=ROOT / 'Reference'):
    return shared_inputs.normalization_discriminant_inputs(reference_directory)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    parser.add_argument('--reference', type=Path, default=ROOT / 'Reference')
    args = parser.parse_args()
    profile, license_text = load_profile(args.reference)
    source = generate(profile, license_text)
    if args.write:
        OUTPUT.write_text(source)
    elif OUTPUT.read_text() != source:
        raise ValueError('Generated IDNA normalization compatibility tables differ')
    print(json.dumps(dict(status='passed', normalizationProfileSHA256=PROFILE_SHA256,
                          propertyDataSourceSHA256=SOURCE_SHA256, generatedSourceSHA256=sha(source.encode()),
                          combiningClassRanges=388, compositionPairs=941, decompositions=2061), sort_keys=True))


if __name__ == '__main__':
    main()
