#!/usr/bin/env python3
"""Generate/check complete Swift locale metadata from frozen CLDR 48.2 data.

Python stdlib only. --check compares the entire generated file, including its
provenance and licensing header; no live download or host locale API is used.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "6241d8889b507a6edc0d6dae7e7812c372b62208ba8649701a819de877eade93"
SCHEMA_SHA256 = "03097cf61a52b4e21b35a2f1d986373b706010ebaba61e89c72921905cf41784"
FINGERPRINT = "9b4f24165b6dd1ee6dbb5f0822abc7bcde49c5b94d35903045826b45e1f30e68"


def generate(data):
    if set(data) != {"aliases", "cldrVersion", "formatVersion", "likelySubtags", "parentLocales", "rightToLeftScripts", "validity"}:
        raise RuntimeError("Unknown locale-data fields")
    if data["formatVersion"] != 1 or data["cldrVersion"] != "48.2":
        raise RuntimeError("CLDR locale format/version differs")
    if set(data["aliases"]) != {"language", "region", "script", "variant"} or set(data["validity"]) != {"languages", "regions", "scripts", "variants"}:
        raise RuntimeError("Unknown aliases/validity fields")
    pairs = {name + "Aliases": rows for name, rows in data["aliases"].items()}
    pairs.update(likelySubtags=data["likelySubtags"], parentLocales=data["parentLocales"])
    sets = {"valid" + name.title(): values for name, values in data["validity"].items()}
    sets["rightToLeftScripts"] = data["rightToLeftScripts"]
    counts = {}
    for name, rows in pairs.items():
        keys = set()
        for row in rows:
            if set(row) != {"from", "to"} or any(not re.fullmatch(r"[A-Za-z0-9 _-]+", row[key]) for key in ("from", "to")):
                raise RuntimeError("Unknown/unsafe pair representation")
            lowered = row["from"].lower()
            if lowered in keys:
                raise RuntimeError(f"Duplicate normalized key in {name}")
            keys.add(lowered)
        counts[name] = len(rows)
    for name, values in sets.items():
        if not values or any(not re.fullmatch(r"[A-Za-z0-9-]+", value) for value in values) or len(set(v.lower() for v in values)) != len(values):
            raise RuntimeError("Unknown/unsafe/duplicate validity representation")
        counts[name] = len(values)
    payload = json.dumps({"pairs": pairs, "sets": sets}, sort_keys=True, separators=(",", ":")).encode()
    payload_sha = hashlib.sha256(payload).hexdigest()
    lines = ["// Generated by Tools/generate_locale_data.py; do not edit.",
             "// Complete CLDR 48.2 metadata; Unicode-3.0 license.",
             "// Notices and license: Reference/THIRD-PARTY-NOTICES.spec.md (Unicode-3.0 text included).",
             f"// Source SHA-256: {SOURCE_SHA256}", f"// Schema SHA-256: {SCHEMA_SHA256}",
             f"// Compiled payload SHA-256: {payload_sha}", "package enum LocaleTables {",
             '    package static let cldrVersion = "48.2"', '    package static let generatorVersion = "1.0.0"',
             f'    package static let dataFingerprint = "{FINGERPRINT}"', f'    package static let sourceSha256 = "{SOURCE_SHA256}"',
             f'    package static let payloadSha256 = "{payload_sha}"']
    for name, rows in pairs.items():
        lines += [f"    package static let {name}: [String: String] = pairs(\"\"\""]
        lines += ["        " + row["from"] + "|" + row["to"] for row in rows]
        lines += ['        """)']
    for name, values in sets.items():
        lines += [f"    package static let {name}: Set<String> = values(\"\"\""]
        line = ""
        for value in values:
            if len(line) + len(value) + 1 > 120:
                lines.append("        " + line)
                line = ""
            line += (" " if line else "") + value
        if line:
            lines.append("        " + line)
        lines += ['        """)']
    lines += ['    private static func pairs(_ text: String) -> [String: String] {',
              '        Dictionary(uniqueKeysWithValues: text.split(separator: "\\n").map { row in',
              '            let parts = row.split(separator: "|", maxSplits: 1, omittingEmptySubsequences: false)',
              '            return (LocaleASCII.lower(String(parts[0])), String(parts[1]))',
              '        })', '    }',
              '    private static func values(_ text: String) -> Set<String> {',
              '        Set(text.split(whereSeparator: { $0 == " " || $0 == "\\n" }).map { LocaleASCII.lower(String($0)) })',
              '    }', '}', '']
    return "\n".join(lines), dict(counts=counts, cldrVersion="48.2", sourceSha256=SOURCE_SHA256,
                                  schemaSha256=SCHEMA_SHA256, payloadSha256=payload_sha)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--refresh", action="store_true")
    parser.add_argument("--reference", type=Path, default=ROOT / "Reference")
    parser.add_argument("--output", type=Path, default=ROOT / "Sources/Lokalized/Data/LocaleTables.swift")
    args = parser.parse_args()
    raw = (args.reference / "cldr-locale-data.json").read_bytes()
    schema = (args.reference / "cldr-locale-data.schema.json").read_bytes()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA256 or hashlib.sha256(schema).hexdigest() != SCHEMA_SHA256:
        raise RuntimeError("CLDR locale input/schema differs from the frozen baseline")
    generated, report = generate(json.loads(raw))
    if args.refresh:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated)
    elif args.output.read_text() != generated:
        raise RuntimeError("Generated locale table differs; use explicit --refresh")
    report.update(status="refreshed" if args.refresh else "verified", generatedSwiftBytes=len(generated.encode()),
                  generatedSwiftSha256=hashlib.sha256(generated.encode()).hexdigest())
    print(json.dumps(report, sort_keys=True))


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, RuntimeError, KeyError) as error:
        print(f"Locale generation refused: {error}", file=sys.stderr)
        sys.exit(1)
