#!/usr/bin/env python3
"""Generate/check pinned Java 21 BMP uppercase and decimal-digit locale rules."""
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import subprocess
import tempfile
import zipfile

from verify_floating_point import verify_jdk

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Sources/Lokalized/Data/LocaleUnicodeTables.swift"
JDK_SOURCES = {
    "java.base/java/lang/Character.java": "b37afc4dab680b9741d2bb8d030f0e141c5191003f451ed7f4fd49e67e73117e",
    "java.base/java/lang/String.java": "449cb9a2b74976b019160caeb9bc16fa76b2bb64be2a626543de859fdbea2b14",
    "java.base/java/lang/StringLatin1.java": "8df1eb808fbe4c0e3989240d5cbe4ce90e55c8fcc9af437af284b6f8e04edf17",
    "java.base/java/lang/StringUTF16.java": "3679f04911b9025b800f9c95170895b9c003afed3d22aa1ae4a9fe2bb9dfb6e5",
}
SOURCE_SHA256 = "c5e48e0d56fcbf64b38bc315a28938cae1322bd433ff3ac55d06426638307ccd"
CAPTURE = r'''
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Locale;
public class LocaleUnicodeCapture {
  public static void main(String[] args) {
    if (!System.getProperty("java.version").equals("21.0.11") ||
        !System.getProperty("java.vendor").equals("Amazon.com Inc."))
      throw new IllegalStateException("wrong JDK");
    for (int code = 0; code < 65536; code++) {
      if (code >= 0xd800 && code <= 0xdfff) continue;
      char value = (char) code;
      int type = Character.getType(value);
      if (Character.isLetter(value) != (type >= 1 && type <= 5) ||
          Character.isDigit(value) != (type == Character.DECIMAL_DIGIT_NUMBER))
        throw new IllegalStateException("category mismatch");
      if (Character.isDigit(value)) System.out.println("D\t" + code);
      String original = String.valueOf(value);
      String upper = original.toUpperCase(Locale.ROOT);
      if (!original.equals(upper)) System.out.println("U\t" + code + "\t" +
          Base64.getEncoder().encodeToString(upper.getBytes(StandardCharsets.UTF_8)));
    }
  }
}
'''


def sha(data: bytes) -> str: return hashlib.sha256(data).hexdigest()


def verify_sources(jdk: Path) -> None:
    verify_jdk(jdk)
    with zipfile.ZipFile(jdk / "lib/src.zip") as archive:
        for path, expected in JDK_SOURCES.items():
            if sha(archive.read(path)) != expected: raise ValueError("JDK source pin differs: " + path)


def capture(jdk: Path) -> tuple[list[tuple[int, str]], list[tuple[int, int]]]:
    verify_sources(jdk)
    with tempfile.TemporaryDirectory(prefix="lokalized-locale-unicode-") as temporary:
        source = Path(temporary) / "LocaleUnicodeCapture.java"
        source.write_text(CAPTURE)
        result = subprocess.run([str(jdk / "bin/java"), str(source)], capture_output=True, check=True)
    upper: list[tuple[int, str]] = []
    digits: list[int] = []
    for line in result.stdout.decode("ascii").splitlines():
        parts = line.split("\t")
        if parts[0] == "D" and len(parts) == 2: digits.append(int(parts[1]))
        elif parts[0] == "U" and len(parts) == 3:
            upper.append((int(parts[1]), base64.b64decode(parts[2]).decode("utf-8")))
        else: raise ValueError("unknown Java Unicode capture record")
    if not upper or not digits or len({code for code, _ in upper}) != len(upper):
        raise ValueError("degenerate Unicode capture")
    ranges: list[tuple[int, int]] = []
    for digit in digits:
        if ranges and digit == ranges[-1][1] + 1: ranges[-1] = (ranges[-1][0], digit)
        else: ranges.append((digit, digit))
    return upper, ranges


def source(upper: list[tuple[int, str]], digits: list[tuple[int, int]]) -> bytes:
    lines = [
        "// Generated by Tools/generate_locale_unicode_tables.py. Do not edit.",
        "// Oracle: Amazon Corretto 21.0.11 (Unicode 15.0); release/source pins in generator.",
        "// Java Character.isDigit(char) and single-BMP-character String.toUpperCase(Locale.ROOT).",
        "package enum LocaleUnicodeTables {",
        "    private static let uppercase: [UInt32: String] = [",
    ]
    for code, value in upper:
        encoded = "".join(f"\\u{{{ord(scalar):X}}}" for scalar in value)
        lines.append(f'        0x{code:04X}: "{encoded}",')
    lines += ["    ]", "    package static func upper(_ text: String) -> String {",
              "        var result = String()", "        for scalar in text.unicodeScalars { result += uppercase[scalar.value] ?? String(scalar) }",
              "        return result", "    }", "    private static let digitRanges: [(UInt16, UInt16)] = ["]
    lines += [f"        (0x{start:04X}, 0x{end:04X})," for start, end in digits]
    lines += ["    ]", "    package static func isDigit(_ unit: UInt16) -> Bool {",
              "        var low = 0, high = digitRanges.count",
              "        while low < high {",
              "            let middle = low + (high - low) / 2",
              "            let (first, last) = digitRanges[middle]",
              "            if unit < first { high = middle }",
              "            else if unit > last { low = middle + 1 }",
              "            else { return true }",
              "        }", "        return false", "    }", "}"]
    return ("\n".join(lines) + "\n").encode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--oracle-check", action="store_true")
    parser.add_argument("--java-home", type=Path)
    args = parser.parse_args()
    if args.check:
        if sha(OUTPUT.read_bytes()) != SOURCE_SHA256: raise ValueError("generated locale Unicode source pin differs")
    else:
        if args.java_home is None: parser.error("--generate/--oracle-check require --java-home")
        expected = source(*capture(args.java_home.resolve()))
        if args.generate: OUTPUT.write_bytes(expected)
        elif OUTPUT.read_bytes() != expected: raise ValueError("live JDK locale Unicode projection differs")
        if sha(expected) != SOURCE_SHA256 and not args.generate: raise ValueError("generated locale Unicode source pin differs")
    print({"status": "passed", "sourceSHA256": sha(OUTPUT.read_bytes()), "mode": "generate" if args.generate else "check" if args.check else "oracle-check"})


if __name__ == "__main__": main()
