#!/usr/bin/env python3
"""Generate/check pinned Unicode 15.0 identifier ranges; no consumer build hook.

--generate requires an explicit pinned JDK 21 home and performs an exhaustive
Java Pattern category sweep. --check needs Python's standard library and the
checked-in sidecar only; neither mode fetches network inputs.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
RELEASE_SHA = "31c8dd26f07b2bd2c394663b57a93879ea139f525c76c730b13956890c151239"
RANGES_SHA = "d1c5f7947c2b761f6f9a7ca5b7ac3d9a0de473b3103698974053461a624a253c"
UNICODE_NOTICE_SHA = "6f72f10d166b2c2e8a395e03e734c5afc852b59aeca73ced124f6b9c96268d53"
JAVA_SOURCE = r'''import java.util.regex.Pattern;
public class IdentifierProjection {
 public static void main(String[] arguments) {
  if (!System.getProperty("java.version").equals("21.0.11") || !System.getProperty("java.vendor").equals("Amazon.com Inc.")) throw new IllegalStateException("Unpinned Java runtime");
  Pattern l=Pattern.compile("\\p{L}"), n=Pattern.compile("\\p{N}"), m=Pattern.compile("\\p{M}");
  StringBuilder out=new StringBuilder();
  int begin=0, previous=0; long letters=0,numbers=0,marks=0;
  for (int cp=0;cp<=0x110000;cp++) {
   int flags=0;
   if (cp<0x110000 && !(cp>=0xd800 && cp<=0xdfff)) {
    String text=new String(Character.toChars(cp));
    boolean letter=l.matcher(text).matches(), number=n.matcher(text).matches(), mark=m.matcher(text).matches();
    int type=Character.getType(cp);
    if (letter!=(type>=1&&type<=5) || number!=(type>=9&&type<=11) || mark!=(type>=6&&type<=8)) throw new IllegalStateException("Pattern/category mismatch");
    if (letter) letters++; if (number) numbers++; if (mark) marks++;
    flags=letter?3:((number||mark)?2:0);
   }
   if (flags!=previous) {
    if (previous!=0) out.append(String.format(java.util.Locale.ROOT,"%06x%06x%d",begin,cp-1,previous));
    begin=cp; previous=flags;
   }
  }
  System.out.println(letters+","+numbers+","+marks);
  System.out.println(out);
 }
}
'''


def digest(data):
    return hashlib.sha256(data).hexdigest()


def validate_ranges(encoded):
    if len(encoded) % 13:
        raise ValueError("Malformed fixed-width identifier ranges")
    previous = -1
    counts = {"letters": 0, "continuations": 0}
    for index in range(0, len(encoded), 13):
        row = encoded[index:index + 13]
        start, end, flags = int(row[:6], 16), int(row[6:12], 16), int(row[12])
        if start <= previous or start > end or end > 0x10FFFF or flags not in (2, 3) or (start <= 0xDFFF and end >= 0xD800):
            raise ValueError("Unordered, overlapping or invalid identifier range")
        if row != f"{start:06x}{end:06x}{flags}":
            raise ValueError("Noncanonical identifier range encoding")
        counts["continuations"] += end - start + 1
        if flags == 3:
            counts["letters"] += end - start + 1
        previous = end
    if digest(encoded.encode("ascii")) != RANGES_SHA:
        raise ValueError("Identifier range projection pin mismatch")
    return counts


def manifest(encoded, counts):
    if counts != [136104, 1831, 2450]:
        raise ValueError("Pinned Unicode 15.0 category counts changed")
    totals = validate_ranges(encoded)
    if totals["letters"] != counts[0] or totals["continuations"] != sum(counts):
        raise ValueError("Identifier category inventory mismatch")
    return {"formatVersion": 1, "identifierUnicodeVersion": "15.0", "oracle": {
        "vendor": "Amazon.com Inc.", "javaVersion": "21.0.11", "build": "Corretto-21.0.11.10.1",
        "releaseFileSHA256": RELEASE_SHA, "javaProjectionSHA256": digest(JAVA_SOURCE.encode("utf-8")),
        "policy": "Java Pattern \\p{L}, \\p{N}, \\p{M}; exhaustive scalar sweep checked against Character.getType categories 1...5,9...11,6...8"},
        "letterScalars": counts[0], "numberScalars": counts[1], "markScalars": counts[2],
        "rangeCount": len(encoded) // 13, "encoding": "13 ASCII bytes per range: six lowercase hex start, six lowercase hex inclusive end, flags digit; 3=L/start+continue,2=N/M/continue",
        "rangesSHA256": digest(encoded.encode("ascii")), "ranges": encoded,
        "notices": {"path": "identifier-notices.json", "unicodeNoticeSHA256": UNICODE_NOTICE_SHA}}


def swift_source(data):
    return f'''// Generated by Tools/generate_identifier_tables.py. Do not edit.
// Oracle: Amazon Corretto 21.0.11 (Unicode 15.0); no host Unicode APIs.
// Range payload SHA-256: {data["rangesSHA256"]}
// Java category projection is derived from OpenJDK runtime behavior, not copied source.
// Unicode 15.0 notices: Reference/identifier-notices.json; see Documentation/IDENTIFIER-DATA.md.
package enum IdentifierTables {{
    package static let unicodeVersion = "15.0"
    package static let rangesSHA256 = "{data["rangesSHA256"]}"
    private static let rangeCount = {data["rangeCount"]}
    private static let ranges: StaticString = "{data["ranges"]}"

    package static func contains(_ scalar: UInt32, start: Bool) -> Bool {{
        guard scalar <= 0x10ffff, !(0xd800...0xdfff).contains(scalar) else {{ return false }}
        let bytes = ranges.utf8Start
        var low = 0
        var high = rangeCount
        while low < high {{
            let middle = low + (high - low) / 2
            let offset = middle * 13
            let first = decodeHex(bytes, offset)
            let last = decodeHex(bytes, offset + 6)
            if scalar < first {{ high = middle }}
            else if scalar > last {{ low = middle + 1 }}
            else {{ return !start || bytes[offset + 12] == 51 }}
        }}
        return false
    }}

    private static func decodeHex(_ bytes: UnsafePointer<UInt8>, _ offset: Int) -> UInt32 {{
        var result: UInt32 = 0
        for index in offset..<(offset + 6) {{
            let byte = bytes[index]
            result = result << 4 | UInt32(byte <= 57 ? byte - 48 : byte - 87)
        }}
        return result
    }}
}}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--java-home", type=Path)
    args = parser.parse_args()
    raw = ROOT / "Reference/identifier-data.json"
    notices = ROOT / "Reference/identifier-notices.json"
    output = ROOT / "Sources/Lokalized/Data/IdentifierTables.swift"
    if args.generate:
        if args.java_home is None:
            parser.error("--generate requires --java-home; no implicit host Unicode/runtime is used")
        if digest((args.java_home / "release").read_bytes()) != RELEASE_SHA:
            raise ValueError("JDK release identity does not match the pinned oracle")
        notice_bytes = (args.java_home / "legal/java.base/unicode.md").read_bytes()
        if digest(notice_bytes) != UNICODE_NOTICE_SHA:
            raise ValueError("JDK Unicode 15.0 notice identity mismatch")
        with tempfile.TemporaryDirectory(prefix="lokalized-unicode-projection-") as directory:
            source = Path(directory) / "IdentifierProjection.java"
            source.write_text(JAVA_SOURCE, encoding="utf-8")
            result = subprocess.run([str(args.java_home / "bin/java"), str(source)], capture_output=True, text=True)
            if result.returncode:
                raise ValueError(result.stderr)
            lines = result.stdout.splitlines()
            data = manifest(lines[1], [int(value) for value in lines[0].split(",")])
        raw.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        notices.write_text(json.dumps(notice_manifest(notice_bytes.decode("utf-8")), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(swift_source(data), encoding="utf-8")
    if args.check and args.java_home is not None:
        parser.error("--check does not use Java; --java-home is only for --generate")
    data = read_json(raw)
    expected = manifest(data["ranges"], [data["letterScalars"], data["numberScalars"], data["markScalars"]])
    if data != expected or output.read_text() != swift_source(expected):
        raise ValueError("Identifier data/source does not match deterministic generator")
    original_notice = read_json(notices)
    if original_notice != notice_manifest(original_notice["unicode"]["content"]):
        raise ValueError("Identifier Unicode notice manifest changed")
    print(json.dumps({"status": "verified", "unicodeVersion": "15.0", "ranges": data["rangeCount"], "rangesSHA256": data["rangesSHA256"], "generatedSwiftSHA256": digest(output.read_bytes())}))


def notice_manifest(text):
    data = text.encode("utf-8")
    if len(data) != 9078 or digest(data) != UNICODE_NOTICE_SHA:
        raise ValueError("Identifier Unicode notice bytes/digest mismatch")
    return {"formatVersion": 1, "oracleReleaseFileSHA256": RELEASE_SHA, "unicode": {
        "sourcePath": "legal/java.base/unicode.md", "unicodeVersion": "15.0.0",
        "bytes": len(data), "sha256": UNICODE_NOTICE_SHA, "content": text}}


def read_json(path):
    def unique(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"{path}: duplicate member {key!r}")
            result[key] = value
        return result
    return json.loads(path.read_bytes(), object_pairs_hook=unique)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Identifier generation/check failed: {error}", file=sys.stderr)
        sys.exit(1)
